Algoritmo "questao 05"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gleison Brito
// Autor(a)    : Gleison Brito
// Data atual  : 19/09/2023
Var
// Seção de Declarações das variáveis 
num, cont:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(num)
para cont de 1 ate 10 faca
     escreval(num, " * ", cont, " = ", num*cont)
fimpara

Fimalgoritmo