Algoritmo "questao 06"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gleison Brito
// Autor(a)    : Gleison Brito
// Data atual  : 13/09/2023
Var
   nota:inteiro
   frequencia:real


Inicio
      leia(nota)
      leia(frequencia)
      
      se (nota >= 6) e (frequencia >= 75) entao
           escreval("Aprovado!")
      senao
           escreval("Reprovado!")
      fimse

Fimalgoritmo