Algoritmo "questao 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2023
Var
   idade:inteiro
   renda:real


Inicio
   leia(idade)
   leia(renda)
   
   se (idade >= 18) e (renda >= 1000) entao
      escreva("Emprestimo liberado")
   senao
      escreva("Emprestimo indisponível")
   fimse


Fimalgoritmo