Algoritmo "questao 03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gleison Brito
// Autor(a)    : Gleison Brito
// Data atual  : 19/09/2023
Var
// Seção de Declarações das variáveis 
num, fat, cont:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(num)

fat <- 1
para cont de 1 ate num faca
     fat <- fat * cont
fimpara

escreva(fat)

Fimalgoritmo