Algoritmo "questao 05"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gleison Brito
// Autor(a)    : Gleison Brito
// Data atual  : 13/09/2023
Var
   numero: inteiro


Inicio
      leia(numero)
      se numero > 0 entao
           escreva(numero, " é positivo")
      senao
          se numero < 0 entao
             escreva(numero, " é negativo")
          senao
               escreva("Você inseriu zero!")
          fimse
      fimse


Fimalgoritmo